version: '2'
services:
  consul-server-1:
    image: my-consul
    container_name: consul-server-1
    ports:
    - "8501:8500"
    - "8601:8600"
    command: 
    - -bootstrap
    - -bootstrap-expect=1
    - -server
    - -datacenter=local-docker
    - -client=0.0.0.0
    - -data-dir=/var/consul
    - -ui
  consul-server-2:
    image: my-consul
    container_name: consul-server-2
    ports:
    - "8502:8500"
    - "8602:8600"
    command: 
    - -bootstrap-expect=2
    - -server
    - -datacenter=local-docker
    - -client=0.0.0.0
    - -data-dir=/var/consul
    - -ui
    - -retry-join=consul-server-1
    - -retry-max=10
    depends_on:
    - consul-server-1
  consul-server-3:
    image: my-consul
    container_name: consul-server-3
    ports:
    - "8503:8500"
    - "8603:8600"
    command: 
    - -bootstrap-expect=2
    - -server
    - -datacenter=local-docker
    - -client=0.0.0.0
    - -data-dir=/var/consul
    - -ui
    - -retry-join=consul-server-1
    - -retry-max=10
    depends_on:
    - consul-server-1